export const SHOW_CONNECTIONS = 'SHOW_CONNECTIONS';
export const HIDE_CONNECTIONS = 'HIDE_CONNECTIONS';

export const UPDATE_INPUT = 'UPDATE_INPUT';

export const SET_LAST_PRICE = 'SET_LAST_PRICE';
export const SET_HIGHEST_BID = 'SET_HIGHEST_BID';
export const SET_LOWEST_ASK = 'SET_LOWEST_ASK';
export const SET_BASE_TOKEN_VOLUME = 'SET_BASE_TOKEN_VOLUME';
export const SET_ORDER_TOKEN_VOLUME = 'SET_ORDER_TOKEN_VOLUME';
export const SET_INPUT_BASE_TOKEN = 'SET_INPUT_BASE_TOKEN';
export const SET_INPUT_ORDER_TOKEN = 'SET_INPUT_ORDER_TOKEN';
export const UPDATE_INPUT_ORDER_TOKEN = 'UPDATE_INPUT_ORDER_TOKEN';
export const UPDATE_INPUT_BASE_TOKEN = 'UPDATE_INPUT_BASE_TOKEN';

export const SET_MARKET_PAIR = 'SET_MARKET_PAIR';
export const SET_ORDER_BOOK = 'SET_ORDER_BOOK';
export const SET_ORDER_BOOK_BIDS = 'SET_ORDER_BOOK_BIDS';
export const SET_ORDER_BOOK_ASKS = 'SET_ORDER_BOOK_ASKS';
export const SET_CHECKING_MARKET = 'SET_CHECKING_MARKET';
export const SHOW_ERROR_DIALOG = 'SHOW_ERROR_DIALOG';
export const SHOW_SUCCESS_DIALOG = 'SHOW_SUCCESS_DIALOG';